/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AiConceptsRouteImport } from './routes/ai-concepts'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ReportRouteImport } from './routes/report'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConceptsRoute = AiConceptsRouteImport.update({
  id: '/ai-concepts',
  path: '/ai-concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-concepts': typeof AiConceptsRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/reminders': typeof RemindersRoute
  '/report': typeof ReportRoute
  '/upload': typeof UploadRoute
  '/account': typeof AuthenticatedAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-concepts': typeof AiConceptsRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/reminders': typeof RemindersRoute
  '/report': typeof ReportRoute
  '/upload': typeof UploadRoute
  '/account': typeof AuthenticatedAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-concepts': typeof AiConceptsRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/reminders': typeof RemindersRoute
  '/report': typeof ReportRoute
  '/upload': typeof UploadRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-concepts'
    | '/assessment'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/onboarding'
    | '/progress'
    | '/reminders'
    | '/report'
    | '/upload'
    | '/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-concepts'
    | '/assessment'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/onboarding'
    | '/progress'
    | '/reminders'
    | '/report'
    | '/upload'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-concepts'
    | '/assessment'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/onboarding'
    | '/progress'
    | '/reminders'
    | '/report'
    | '/upload'
    | '/_authenticated/account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiConceptsRoute: typeof AiConceptsRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  RemindersRoute: typeof RemindersRoute
  ReportRoute: typeof ReportRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-concepts': {
      id: '/ai-concepts'
      path: '/ai-concepts'
      fullPath: '/ai-concepts'
      preLoaderRoute: typeof AiConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiConceptsRoute: AiConceptsRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  RemindersRoute: RemindersRoute,
  ReportRoute: ReportRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
